# Generated by Django 6.1.1 on 2026-09-12 06:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="SEO-friendly URL part, e.g. 'home-furniture'. Auto-generated if left empty.", max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('active', models.BooleanField(default=True, help_text='Inactive categories are hidden from the website (but stay in admin).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code customers type in, e.g. SAVE20. Stored in UPPERCASE.', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10) or fixed amount (e.g. 200), depending on type.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coupon only applies when the cart subtotal is at least this much.', max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='For percentage coupons: cap the discount at this amount. Empty = no cap.', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Coupon becomes usable at this moment (empty = immediately).', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Coupon stops working after this moment (empty = never).', null=True)),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can ever be used. Empty = unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL part, auto-generated from the name if empty.', max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='One or two lines shown on product cards and at the top of the detail page.', max_length=300)),
                ('description', models.TextField(help_text='Full description shown on the product page.')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit. Auto-generated if left empty.', max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original price (shown crossed-out when on sale).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sell price during a sale. Leave empty when there is no discount.', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Units available. 0 = out of stock (cannot be added to cart).')),
                ('image', models.ImageField(help_text='Main product photo (JPEG/PNG/WebP, a few hundred KB is enough).', upload_to='products/')),
                ('featured', models.BooleanField(default=False, help_text="Show on the home page 'Featured products' section.")),
                ('active', models.BooleanField(default=True, help_text='Inactive products are hidden from the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='If a brand is deleted, its products simply keep their other data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(help_text='Deleting a category also deletes its products.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Deleting a product also deletes its gallery photos.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'product images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(help_text='Deleting a product also deletes its reviews.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(help_text='The customer who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'active'], name='products_pr_feature_e2f0cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_review_per_user_per_product'),
        ),
    ]
